ARG PYTHON_VERSION=latest

FROM python:$PYTHON_VERSION

ARG POETRY_VERSION

ENV POETRY_HOME=/opt/poetry
ENV PATH=${PATH}:$POETRY_HOME/bin
ENV POETRY_VERSION=$POETRY_VERSION

RUN apk add --no-cache --virtual gcc libc-dev libffi-dev && \
    python3 -m venv $POETRY_HOME && $POETRY_HOME/bin/pip install poetry==$POETRY_VERSION && \
    apk remove gcc libc-dev libffi-dev
